version: "3.7"

services:

  postgres:
    image: postgres:alpine
    restart: always
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: FlightDB
    volumes: 
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - "k-network"

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - "postgres"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "5050:80"
    networks:
      - "k-network"

  webapi:
    build: ./BookingService.Api/
    restart: always
    depends_on: 
      - "postgres"
    ports:
      - "8080:80"
      # - "8443:443"
    networks:
      - "k-network"

  client: 
    build: ./BookingService.Client/ 
    volumes:
      - out:/out
    working_dir: /app/
    command: /bin/sh /app/copy.sh

  tg_bot:
    build: ./BookingService.TgBot/
    restart: always
    volumes:
      - out:/out
    depends_on:
      - "webapi"
    ports:
      - "1234:1234"
    command: /bin/sh /app/copy.sh
    stdin_open: true
    tty: true
    networks:
      - "k-network"

volumes:
  out:

networks:
  k-network:
    driver: bridge
